[package]
name = "m31jubjub"
version = "0.1.0"
edition = "2021"

[dependencies]

p3-mersenne-31 = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}
p3-field = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}
p3-poseidon2 = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}
p3-symmetric = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}


primitives = {git="https://github.com/zeropoolnetwork/sharded-storage.git", branch="main"}

ark-ff = "0.4.2"
ark-serialize = "*"
generic-array = { version = "*" }
num-bigint = "0.4.6"
sha3 = "0.10.8"

hmac = "0.12.1"
sha2 = "0.10.8"
bincode = "1.3.3"
base58 = "0.2"
ripemd = "0.1"
pbkdf2 = "0.12"

rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
libc-print = "*"
